config/routes.rb
Rails.application.routes.draw do
mount Spree::Core::Engine, at: '/'
Spree::Core::Engine.add_routes do
    namespace :api, defaults: { format: 'json' } do
      namespace :v1 do
        namespace :products do
          resources :export, :all, only: [:index,:create,:new], :defaults => { :format => 'xml' }
        end
        get "/products/export/all/" => "products/export#index", :defaults => { :format => 'xml' }
        get "/products/export/recent/" => "products/export#recent", :defaults => { :format => 'xml' }
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_spree_user!
  def index
     user = Spree::user_class.first
     api_key = user.spree_api_key
  end
end

app/controllers/spree/api/v1/products/export_controller.rb
module Spree
  module Api
    module V1
      module Products
        class ExportController < Spree::Api::BaseController
          def index
            @products = product_scope
            expires_in 15.minutes, public: true

            headers['Surrogate-Control'] = "max-age=#{15.minutes}"
            respond_with(@products) do |format|
              format.xml { render xml: collect_data.to_xml }
            end
          end

          def new
            @product = product_scope.new
          end

          # def create
          #   uri = URI.parse("http://localhost:3000/api/v1/products")
          #   request = Net::HTTP::Post.new(uri)
          #   request["X-Spree-Token"] = "f10843e134b925f71ddc93eef7b5dbd3c2b69eba1831decc"
          #   request.set_form_data(
          #     "product[name]" => "Headphones1",
          #     "product[price]" => "100",
          #     "product[shipping_category_id]" => "1",
          #   )

          #   req_options = {
          #     use_ssl: uri.scheme == "https",
          #   }

          #   response = Net::HTTP.start(uri.hostname, uri.port, req_options) do |http|
          #     http.request(request)
          # end
          # end

          def collect_data
            products_hash = []
            @products.each do |product|
              products_hash << {
                id: product.id,
                name: product.name,
                description: product.description,
                price: product.price,
                taxons: collect_taxons(product),
                variants: collect_variants(product)
              }
            end
            products_hash
          end

          def collect_taxons(product)
            taxons_array = []
            product.taxons.each do |taxon|
              array_of_strings = []
              taxon.attributes.each do |attrib|
                array_of_strings << attrib[0] + ':' + ' ' + attrib[1].to_s
              end
              taxons_array << array_of_strings
            end
            taxons_array
          end

          def collect_variants(product)
            variants_array = []
            product.variants.each do |variant|
              array_of_strings = []
              variant.attributes.each do |attrib|
                array_of_strings << attrib[0] + ':' + ' ' + attrib[1].to_s
              end
              variants_array << array_of_strings
            end
            variants_array
          end

          def recent
            @products = product_scope
            now = Time.now
            @products = @products.where(updated_at: (now - 24.hours)..now)
            expires_in 15.minutes, public: true
            headers['Surrogate-Control'] = "max-age=#{15.minutes}"
            respond_with(@products) do |format|
              format.xml { render xml: collect_data.to_xml }
            end
          end
        end
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/spree/address/_form.html.erb
<% address_id = address_type.chars.first %>

<div class="inner" data-hook=<%="#{address_type}_inner" %>>
  <div class="form-group" id=<%="#{address_id}firstname" %>>
    <%= form.label :firstname do %>
      <%= Spree.t(:first_name) %><abbr class="required" title="required">*</abbr>
    <% end %>
    <%= form.text_field :firstname, class: 'form-control', required: true %>
  </div>
  <div class="form-group" id=<%="#{address_id}lastname" %>>
    <%= form.label :lastname do %>
      <%= Spree.t(:last_name) %><abbr class="required" title="required">*</abbr>
    <% end %>
    <%= form.text_field :lastname, class: 'form-control', required: true %>
  </div>
  <% if Spree::Config[:company] %>
    <div class="form-group" id=<%="#{address_id}company" %>>
      <%= form.label :company, Spree.t(:company) %>
      <%= form.text_field :company, class: 'form-control' %>
    </div>
  <% end %>
  <div class="form-group" id=<%="#{address_id}address1" %>>
    <%= form.label :address1 do %>
      <%= Spree.t(:street_address) %><abbr class="required" title="required">*</abbr>
    <% end %>
    <%= form.text_field :address1, class: 'form-control required' %>
  </div>
  <div class="form-group" id=<%="#{address_id}address2" %>>
    <%= form.label :address2, Spree.t(:street_address_2) %>
    <%= form.text_field :address2, class: 'form-control' %>
  </div>
  <div class="form-group" id=<%="#{address_id}city" %>>
    <%= form.label :city do %>
      <%= Spree.t(:city) %><abbr class="required" title="required">*</abbr>
    <% end %>
    <%= form.text_field :city, class: 'form-control', required: true %>
  </div>

  <div class="form-group" id=<%="#{address_id}country" %>>
    <%= form.label :country_id do %>
      <%= Spree.t(:country) %><abbr class="required" title="required">*</abbr>
    <% end %>
    <span id=<%="#{address_id}country-selection" %>>
      <%= form.collection_select :country_id, available_countries, :id, :name, {}, { class: 'form-control', required: true } %>
    </span>
  </div>

  <% if Spree::Config[:address_requires_state] %>
    <div class="form-group" id=<%="#{address_id}state" %>>
      <% have_states = !address.country.states.empty? %>
      <%= form.label :state do %>
        <%= Spree.t(:state) %><abbr class='required' title="required" id=<%="#{address_id}state-required"%>>*</abbr>
      <% end %>

      <%== state_elements = [
         form.collection_select(:state_id, address.country.states,
                            :id, :name,
                            {include_blank: true},
                            {class: have_states ? 'form-control' : 'hidden',
                            required: have_states,
                            disabled: !have_states}) +
         form.text_field(:state_name,
                            class: !have_states ? 'form-control' : 'hidden',
                            required: !have_states,
                            disabled: have_states)
         ].join.gsub('"', "'").gsub("\n", "")
      %>
    </div>
      <noscript>
        <%= form.text_field :state_name, class: 'form-control', required: true %>
      </noscript>
  <% end %>

  <div class="form-group" id=<%="#{address_id}zipcode" %>>
    <%= form.label :zipcode do %>
      <%= Spree.t(:zip) %><% if address.require_zipcode? %><abbr class="required" title="required">*</abbr><% end %>
    <% end %>
    <%= form.text_field :zipcode, class: 'form-control', required: address.require_zipcode? %>
  </div>


  <div class="form-group" id=<%="#{address_id}phone" %>>
    <%= form.label :phone do %>
      <%= Spree.t(:phone) %><% if address.require_phone? %><abbr class="required" title="required">*</abbr><% end %>
    <% end %>
    <%= form.phone_field :phone, class: 'form-control', required: address.require_phone? %>
  </div>
  <% if Spree::Config[:alternative_shipping_phone] %>
    <div class="form-group" id=<%="#{address_id}altphone" %>>
      <%= form.label :alternative_phone, Spree.t(:alternative_phone) %>
      <%= form.phone_field :alternative_phone, class: 'form-control' %>
    </div>
  <% end %>
</div>

app/views/spree/api/v1/products/export/new.html.erb
<h1>Hello</h1>

app/views/spree/checkout/_address.html.erb
<% @addresses = try_spree_current_user ? try_spree_current_user.addresses : [] %>

<div class="row">
  <% ['billing', 'shipping'].each do |address_type|
    address_name = "#{address_type[0...4]}_address" %>
    <div class="col-12 col-md-6 mb-4" data-hook="<%= address_type %>_fieldset_wrapper">
      <div class="card card-default" id="<%= address_type %>" data-hook>
        <div class="card-header">
          <h5 class="mb-0">
            <%= Spree.t(address_type + '_address') %>
          </h5>
        </div>
        <div class="card-body">
          <% if address_type == 'shipping' %>
            <div class="mb-0 form-check" data-hook="use_billing">
              <%= label_tag :order_use_billing, id: 'use_billing' do %>
                <%= check_box_tag 'order[use_billing]', '1', @order.shipping_eq_billing_address?, { class: 'form-check-input'} %>
                <%= Spree.t(:use_billing_address) %>
              <% end %>
            </div>
          <% end %>
          <% if @addresses.present? %>
          <div class="select_address">
            <div class="form-group">
              <% @addresses.each_with_index do |address, idx| %>
              <span class="d-block mb-2" id="<%= [address_type, dom_id(address)].join('_') %>">
                <label class="form-check-label">
                  <%= form.radio_button "#{address_name}_id", address.id, checked: (address.id == try_spree_current_user["#{address_name}_id"] || idx == 0) %> <%= address.to_s.html_safe %>
                </label>
                <a class="mb-3" href="<%= edit_address_path(address) %>" data-hook="edit_address"><%= Spree.t(:edit) %></a>
              </span>
              <% end %>
              <div class="form-check">
                <label class="form-check-label">
                  <%= form.radio_button "#{address_name}_id", 0, class: 'form-check-input' %> <%= Spree.t('address_book.other_address') %>
                </label>
              </div>
            </div>
          </div>
          <% end %>
          <%= form.fields_for address_name do |address_form| %>
            <div class="inner" data-hook=<%="#{address_type}_inner" %>>
              <%= render partial: 'spree/addresses/form', locals: {
                address_name: address_name,
                address_form: address_form,
                address_type: address_type,
                address: Spree::Address.default
              } %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

<div class="card text-right form-buttons my-4" data-hook="buttons">
  <div class="card-body">
    <%= submit_tag Spree.t(:save_and_continue), class: 'btn btn-lg btn-success' %>
    <% if try_spree_current_user %>
      <span data-hook="save_user_address" class='save-user-address-wrapper'>
        &nbsp; &nbsp;
        <%= check_box_tag 'save_user_address', '1', try_spree_current_user.respond_to?(:persist_order_address) %>
        <%= label_tag :save_user_address, Spree.t(:save_my_address) %>
      </span>
    <% end %>
  </div>
</div>

app/views/spree/checkout/_confirm.html.erb
<div class="card" id="order_details" data-hook>
  <div class="card-header">
    <h3 class="card-title mb-0 h5"><%= Spree.t(:confirm) %></h3>
  </div>
  <div class="card-body">
    <%= render partial: 'spree/shared/order_details', locals: { order: @order } %>
  </div>
</div>

<div class="card text-right form-buttons mt-4" data-hook="buttons">
  <div class="card-body">
    <% if @order.using_store_credit? %>
      <%= button_tag Spree.t('store_credit.remove'), name: 'remove_store_credit', class: 'continue btn' %>
    <% end %>
    <%= submit_tag Spree.t(:place_order), class: 'btn btn-lg btn-success' %>
    <script>Spree.disableSaveOnClick();</script>
  </div>
</div>

app/views/spree/checkout/_delivery.html.erb
<div class="card" id='shipping_method' data-hook>
  <div class="card-header">
    <h3 class="card-title mb-0 h5"><%= Spree.t(:delivery) %></h3>
  </div>
  <div class="card-body" data-hook="shipping_method_inner">
    <div id="methods">
      <%= form.fields_for :shipments do |ship_form| %>
        <div class="shipment">
          <h4 class="stock-location h5" data-hook="stock-location">
            <%= Spree.t(:package_from) %>
            <strong class="stock-location-name" data-hook="stock-location-name">
              <%= ship_form.object.stock_location.name %>
            </strong>
          </h4>

          <table class="table stock-contents" data-hook="stock-contents">
            <colgroup>
              <col style="width: 10%;" />
              <col style="width: 60%;" />
              <col style="width: 10%;" />
              <col style="width: 20%;" />
            </colgroup>
            <thead>
              <tr class="active">
                <th></th>
                <th align='left'><%= Spree.t(:item) %></th>
                <th><%= Spree.t(:qty) %></th>
                <th><%= Spree.t(:price) %></th>
              </tr>
            </thead>
            <tbody>
              <% ship_form.object.manifest.each do |item| %>
                <tr class="stock-item">
                  <td class="item-image"><%= mini_image(item.variant) %></td>
                  <td class="item-name"><%= item.variant.name %></td>
                  <td class="item-qty"><%= item.quantity %></td>
                  <td class="item-price"><%= display_price(item.variant) %></td>
                </tr>
              <% end %>
            </tbody>
          </table>

          <h4 class="stock-shipping-method-title h5">
            <%= Spree.t(:shipping_method) %>
          </h4>

          <ul class="list-group shipping-methods">
            <% ship_form.object.shipping_rates.each do |rate| %>
              <li class="list-group-item shipping-method">
                <label>
                  <%= ship_form.radio_button :selected_shipping_rate_id,
                    rate.id,
                    data: {
                      behavior: 'shipping-method-selector',
                      cost: rate.display_cost
                  } %>
                  <span class="rate-name"><%= rate.name %></span>
                  <span class="badge badge-secondary rate-cost"><%= rate.display_cost %></span>
                </label>
              </li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <% if @differentiator.try(:missing?) %>
        <div class="shipment unshippable">
          <h3 class="stock-location mb-0 h5" data-hook="stock-location">
            <%= Spree.t(:unshippable_items) %>
          </h3>
          <table class="table stock-contents" data-hook="stock-missing">
            <colgroup>
              <col style="width: 10%;" />
              <col style="width: 60%;" />
              <col style="width: 10%;" />
              <col style="width: 20%;" />
            </colgroup>
            <thead>
              <th></th>
              <th align='left'><%= Spree.t(:item) %></th>
              <th><%= Spree.t(:qty) %></th>
              <th><%= Spree.t(:price) %></th>
            </thead>
            <tbody>
              <% @differentiator.missing.each do |variant, quantity| %>
                <tr class="stock-item">
                  <td class="item-image"><%= mini_image(variant) %></td>
                  <td class="item-name"><%= variant.name %></td>
                  <td class="item-qty"><%= quantity %></td>
                  <td class="item-price"><%= display_price(variant) %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      <% end %>
    </div>
    <% if Spree::Config[:shipping_instructions] %>
      <p id="minstrs" data-hook>
        <h4 class="h5">
          <%= Spree.t(:shipping_instructions) %>
        </h4>
        <%= form.text_area :special_instructions, cols: 40, rows: 4, class: "form-control" %>
      </p>
    <% end %>
  </div>
</div>

<div class="card my-4 text-right form-buttons" data-hook="buttons">
  <div class="card-body">
    <%= submit_tag Spree.t(:save_and_continue), class: 'btn btn-lg btn-success' %>
  </div>
</div>

<%= javascript_include_tag 'spree/frontend/checkout/shipment' %>

app/views/spree/checkout/_payment.html.erb
<div class="card" id="payment" data-hook>
  <div class="card-header">
    <h3 class="card-title mb-0 h5">
      <%= Spree.t(:payment_information) %>
    </h3>
  </div>

  <div class="card-body" data-hook="checkout_payment_step">
    <% if @payment_sources.present? %>
      <div class="card_options">
        <%= radio_button_tag 'use_existing_card', 'yes', true %>
        <label for="use_existing_card_yes">
          <%= Spree.t(:use_existing_cc) %>
        </label>
        <%= radio_button_tag 'use_existing_card', 'no' %>
        <label for="use_existing_card_no">
          <%= Spree.t(:use_new_cc_or_payment_method) %>
        </label>
      </div>

      <div id="existing_cards">
        <p class="form-group" data-hook="existing_cards">
          <table class="existing-credit-card-list">
            <tbody>
              <% @payment_sources.each do |card| %>
                <tr id="<%= dom_id(card,'spree')%>" class="<%= cycle('even', 'odd') %>">
                  <td>
                    <%= radio_button_tag "order[existing_card]", card.id, (card == @payment_sources.first), { class: "existing-cc-radio" }  %>
                  </td>
                  <td><%= card.name %></td>
                  <td><%= card.display_number %></td>
                  <td><%= card.month %> / <%= card.year %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </p>
      </div>
    <% end %>

    <%= render partial: 'spree/checkout/payment/storecredit' %>

    <ul class="list-group" id="payment-method-fields" data-hook>
      <% @order.available_payment_methods.each do |method| %>
        <li class="list-group-item radio">
          <label>
            <%= radio_button_tag "order[payments_attributes][][payment_method_id]", method.id, method == @order.available_payment_methods.first %>
            <%= Spree.t(method.name, scope: :payment_methods, default: method.name) %>
          </label>
        </li>
      <% end %>
    </ul>

    <ul id="payment-methods" class="list-unstyled position-relative" data-hook>
      <% @order.available_payment_methods.each do |method| %>
        <li id="payment_method_<%= method.id %>" class="<%= 'last' if method == @order.available_payment_methods.last %>" data-hook>
          <fieldset>
            <%= render partial: "spree/checkout/payment/#{method.method_type}", locals: { payment_method: method } %>
          </fieldset>
        </li>
      <% end %>
    </ul>


    <% if Spree::Frontend::Config[:coupon_codes_enabled] %>
      <p class='field mb-0' data-hook='coupon_code'>
        <%= form.label :coupon_code %>
        <%= form.text_field :coupon_code, class: 'form-control' %>
      </p>
    <% end %>
  </div>
</div>

<div class="card text-right form-buttons my-4" data-hook="buttons">
  <div class="card-body">
    <%= submit_tag Spree.t(:save_and_continue), class: 'btn btn-lg btn-success primary' %>
    <script>Spree.disableSaveOnClick();</script>
  </div>
</div>

app/views/spree/checkout/_summary.html.erb
<h3><%= Spree.t(:order_summary) %></h3>

<div class="table-responsive">
  <table class="table" data-hook="order_summary">
    <tbody>
      <tr data-hook="item_total">
        <td><strong><%= Spree.t(:item_total) %>:</strong></td>
        <td><strong><%= order.display_item_total.to_html %></strong></td>
      </tr>

      <% if order.line_item_adjustments.nonzero.exists? %>
        <tbody data-hook="order_details_promotion_adjustments">
          <% order.line_item_adjustments.nonzero.promotion.eligible.group_by(&:label).each do |label, adjustments| %>
            <tr class="total">
              <td><%= label %></td>
              <td><%= Spree::Money.new(adjustments.sum(&:amount), currency: order.currency).to_html %></td>
            </tr>
          <% end %>
        </tbody>
      <% end %>

      <tbody data-hook="order_details_tax_adjustments">
        <% order.all_adjustments.nonzero.tax.eligible.group_by(&:label).each do |label, adjustments| %>
          <tr class="total">
            <td><%= label %></td>
            <td><%= Spree::Money.new(adjustments.sum(&:amount), currency: order.currency).to_html %></td>
          </tr>
        <% end %>
      </tbody>

      <% if order.passed_checkout_step?("address") && order.shipments.any? %>
        <tr data-hook="shipping_total">
          <td><%= Spree.t(:shipping_total) %>:</td>
          <% shipping_total = Spree::Money.new(order.shipments.to_a.sum(&:cost), currency: order.currency) %>
          <td data-hook='shipping-total' data-currency='<%= Money::Currency.find(order.currency).symbol %>' thousands-separator='<%= shipping_total.thousands_separator %>' decimal-mark='<%= shipping_total.decimal_mark %>'><%= shipping_total.to_html %></td>
        </tr>

        <% if order.shipment_adjustments.nonzero.exists? %>
          <tbody data-hook="order_details_shipment_promotion_adjustments">
            <% order.shipment_adjustments.nonzero.promotion.eligible.group_by(&:label).each do |label, adjustments| %>
              <tr class="total">
                <td><%= label %>:</td>
                <td><%= Spree::Money.new(adjustments.sum(&:amount), currency: order.currency).to_html %></td>
              </tr>
            <% end %>
          </tbody>
        <% end %>
      <% end %>

      <% if order.adjustments.nonzero.eligible.exists? %>
        <tbody id="summary-order-charges" data-hook>
          <% order.adjustments.nonzero.eligible.each do |adjustment| %>
          <% next if (adjustment.source_type == 'Spree::TaxRate') and (adjustment.amount == 0) %>
            <tr class="total">
              <td><%= adjustment.label %>:</td>
              <td><%= adjustment.display_amount.to_html %></td>
            </tr>
          <% end %>
        </tbody>
      <% end %>

      <tr data-hook="order_total">
        <td><strong><%= Spree.t(:order_total) %>:</strong></td>
        <td>
          <strong>
            <span id='summary-order-total' class="lead text-primary" data-currency="<%= Money::Currency.find(order.currency).symbol %>"><%= order.display_total.to_html %></span>
          </strong>
        </td>
      </tr>

      <% if order.using_store_credit? %>
        <tr data-hook="order_details_store_credit">
          <td><strong><%= Spree.t(:store_credit_name) %>:</strong></td>
          <td><span id='summary-store-credit'><%= order.display_total_applied_store_credit.to_html %></span></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/spree/checkout/edit.html.erb
<% @body_id = 'checkout-page' %>

<div id="checkout" data-hook>
  <%= render partial: 'spree/shared/error_messages', locals: { target: @order } %>

  <div class="row align-items-center" data-hook="checkout_header">
    <div class="col-md-3 mb-4">
      <h1 class="mb-0" data-hook="checkout_title"><%= Spree.t(:checkout) %></h1>
    </div>
    <div class="col-md-9 mb-4" data-hook="checkout_progress">
      <%= checkout_progress %>
    </div>
  </div>

  <div class="row" data-hook="checkout_content">
    <div class="<%= if @order.state != 'confirm' then 'col-md-9' else 'col-md-12' end %>" data-hook="checkout_form_wrapper">
      <%= form_for @order, url: update_checkout_path(@order.state), html: { id: "checkout_form_#{@order.state}" } do |form| %>
        <% if @order.state == 'address' || !@order.email? %>
          <div class="card card-default mb-4">
            <div class="card-body">
              <div class="form-group">
                <%= form.label :email %>
                <%= form.email_field :email, class: 'form-control', required: true %>
              </div>
            </div>
          </div>
        <% end %>
        <%= form.hidden_field :state_lock_version %>
        <%= render @order.state, form: form %>
      <% end %>
    </div>
    <% if @order.state != 'confirm' %>
      <div id="checkout-summary" data-hook="checkout_summary_box" class="col-md-3">
        <%= render partial: 'summary', locals: { order: @order } %>
      </div>
    <% end %>
  </div>
</div>

<script>
  Spree.current_order_id = "<%= @order.number %>"
  Spree.current_order_token = "<%= @order.token %>"
</script>

app/views/spree/orders/_adjustment_row.html.erb
<% if adjustments.sum(&:amount) != 0 %>
  <tr class="adjustment">
    <td colspan="4" align='right'><h5><%= type %>: <%= label %></h5></td>
    <td colspan='2'>
      <h5><%= Spree::Money.new(adjustments.sum(&:amount), currency: @order.currency) %></h5>
    </td>
  </tr>
<% end %>

app/views/spree/orders/_line_item.html.erb
<% variant = line_item.variant %>

<%= order_form.fields_for :line_items, line_item do |item_form| %>
  <tr class="line-item">
    <td class="cart-item-image" data-hook="cart_item_image">
      <% if variant.images.length == 0 %>
        <%= link_to small_image(variant.product), variant.product %>
      <% else %>
        <%= link_to image_tag(main_app.url_for(variant.images.first.url(:small))), variant.product %>
      <% end %>
    </td>
    <td class="cart-item-description" data-hook="cart_item_description">
      <h4><%= link_to line_item.name, product_path(variant.product) %></h4>
      <%= variant.options_text %>
      <% if line_item.insufficient_stock? %>
        <span class="out-of-stock">
          <%= Spree.t(:out_of_stock) %>&nbsp;&nbsp;<br />
        </span>
      <% end %>
      <span class="line-item-description" data-hook="line_item_description">
        <%= line_item_description_text(line_item.description) %>
      </span>
    </td>
    <td class="lead text-primary cart-item-price" data-hook="cart_item_price">
      <%= line_item.single_money.to_html %>
    </td>
    <td class="cart-item-quantity" data-hook="cart_item_quantity" valign="center">
      <%= item_form.number_field :quantity, min: 0, class: "form-control line_item_quantity", size: 5 %>
    </td>
    <td class="lead text-primary cart-item-total" data-hook="cart_item_total">
      <%= line_item.display_amount.to_html unless line_item.quantity.nil? %>
    </td>
    <td class="cart-item-delete" data-hook="cart_item_delete">
      <%= link_to content_tag(:span, '', class: 'glyphicon glyphicon-minus-sign'), '#', class: 'delete', id: "delete_#{dom_id(line_item)}" %>
    </td>
  </tr>
<% end %>

app/views/spree/orders/edit.html.erb
<% @body_id = 'cart' %>

<div data-hook="cart_container" class="col-12">
  <h1><%= Spree.t(:shopping_cart) %></h1>

  <% if @order.line_items.empty? %>
    <div data-hook="empty_cart">
      <div class="alert alert-info"><%= Spree.t(:your_cart_is_empty) %></div>
      <p>
        <%= link_to Spree.t(:continue_shopping), products_path, class: 'btn btn-outline-secondary' %>
      </p>
    </div>
  <% else %>
    <div data-hook="outside_cart_form">
      <%= form_for @order, url: update_cart_path, html: { id: 'update-cart' } do |order_form| %>
        <div data-hook="inside_cart_form">

          <div data-hook="cart_items" class="table-responsive">
            <%= render partial: 'form', locals: { order_form: order_form } %>
          </div>

          <div class="row">
            <% if Spree::Frontend::Config[:coupon_codes_enabled] %>
              <div class='col-md-6 form-inline' data-hook='coupon_code'>
                <%= order_form.label :coupon_code, class: 'mr-2' %>
                <div class="input-group">
                  <%= order_form.text_field :coupon_code, size: '30', class: 'form-control' %>
                  <div class="input-group-append">
                    <%= button_tag Spree.t(:coupon_code_apply), class: 'btn btn-outline-secondary' %>
                  </div>
                </div>
              </div>
            <% end %>

            <div class="links col-md-6 d-flex justify-content-end" data-hook="cart_buttons">
              <div class="form-group">
                <%= button_tag class: 'btn btn-primary', id: 'update-button' do %>
                  <%= Spree.t(:update) %>
                <% end %>
                <%= button_tag class: 'btn btn-lg btn-success', id: 'checkout-link', name: 'checkout' do %>
                  <%= Spree.t(:checkout) %>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>

    <div id="empty-cart" class="mt-4" data-hook>
      <%= form_tag empty_cart_path, method: :put do %>
        <p id="clear_cart_link" data-hook>
          <%= submit_tag Spree.t(:empty_cart), class: 'btn btn-outline-secondary' %>
          <%= Spree.t(:or) %>
          <%= link_to Spree.t(:continue_shopping), products_path, class: 'continue' %>
        </p>
      <% end %>
    </div>
  <% end %>
</div>

<script>
  Spree.current_order_token = "<%= @order.token %>"
</script>

app/views/spree/products/_promotions.html.erb
<% promotions = @product.possible_promotions %>

<% if promotions.any? %>
  <div id="promotions">
    <h3><%= Spree.t(:promotions) %></h3>
    <% promotions.each do |promotion| %>
    <div class="card mb-3 bg-light">
      <div class="card-body p-1">
        <h4><%= promotion.name %></h4>
        <p><%= promotion.description %></p>
        <% if promotion.products.any? %>
          <ul>
            <% promotion.products.each do |product| %>
              <li><%= link_to product.name, product_path(product) %></li>
            <% end %>
          </ul>
        <% end %>
      </div>
    </div>  
    <% end %>
  </div>
<% end %>